[package]
name = "qoa-encode-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1", features = ["extern_crate_std"] }
thiserror = "1"

[dev-dependencies]
hound = "3"
